name: Clear Contributors List

on:
  workflow_dispatch:

jobs:
  clear-contributors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}

    - name: Set git identity
      run: |
        git config --local user.email "shidang233@outlook.com"
        git config --local user.name "yunshuangqwq"

    - name: Clear contributors in README
      run: |
        if grep -q '<!-- readme: contributors -start -->' README.md; then
          sed -i '/<!-- readme: contributors -start -->/,/<!-- readme: contributors -end -->/d' README.md
          git add README.md
          git commit -am "Clear contributors list"
          git push
        else
          echo "清除贡献者名单"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}