name: Clear Contributors List

on:
  workflow_dispatch:

jobs:
  clear-contributors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}

    - name: Set git identity
      run: |
        git config --local user.email "79011008+yunshuangqwq@users.noreply.github.com"
        git config --local user.name "yunshuangqwq"

    - name: Clear contributors in README
      run: |
        sed -i '/<!-- readme: contributors -start -->/,/<!-- readme: contributors -end -->/{/<!-- readme: contributors -start -->/!{/<!-- readme: contributors -end -->/!d}}' README.md

        if git diff --quiet README.md; then
          echo "No changes to commit."
        else
          git add README.md
          git commit -m "Clear contributors list"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}