## name: Test

on:
  [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "setup pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "setup node"
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - name: "Install"
        run: "pnpm install"

      - name: "MarkdownLint Check"
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: 'docs*/**/*.md'

      - name: "Build"
        run: "pnpm run build"