name: Build and Deploy GitBook

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/wiki.yml'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'  # 使用Node.js 12版本，这是社区推荐的版本

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook --version  # 打印版本信息，确认安装成功

      - name: Update graceful-fs
        run: |
          cd $(npm root -g)/gitbook-cli/node_modules/npm/node_modules/graceful-fs/
          npm install graceful-fs@latest --save

      - name: Install GitBook plugins
        run: |
          cd docs
          npm install
          gitbook install

      - name: Build with gitbook
        run: |
          cd docs
          gitbook build
          mv _book ..  # 移动构建输出到根目录

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book