name: Deploy GitBook to Main Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install GitBook CLI
        run: sudo npm install -g gitbook-cli@2.1.2

      - name: Install GitBook plugins
        run: gitbook install ./docs

      - name: Build GitBook
        run: gitbook build ./docs

      - name: Deploy to Main Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: ./docs/_book
          CLEAN: true