name: Deploy GitBook with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/wiki.yml'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '10.21.0'

      - name: Install gitbook-cli
        run: |
          npm install -g gitbook-cli
          gitbook --version  # 打印版本信息，确认安装成功

      - name: Install GitBook plugins and build
        run: |
          cd docs
          npm install
          gitbook install
          gitbook build
          mv _book ..  # 移动构建输出到根目录

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./_book