name: Convert Office Files to Markdown

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # MarkItDown需要Python 3.10或更高版本

    - name: Install dependencies
      run: |
        pip install markitdown  # 安装MarkItDown库
        sudo apt-get update
        sudo apt-get install -y ffmpeg  # 安装ffmpeg
      shell: bash

    - name: Create output directory
      run: |
        mkdir -p zhdocs/cp  # 创建输出目录，如果不存在

    - name: Run conversion script
      run: |
        python convert_to_markdown.py
      shell: bash

    - name: Configure Git credentials
      run: |
        git config --local user.email "79011008+yunshuangqwq@users.noreply.github.com"
        git config --local user.name "yunshuangqwq"
      shell: bash

    - name: Check for Markdown files
      id: check_files
      run: |
        md_files=()
        while IFS= read -r file; do
          md_files+=("$file")
        done < <(git ls-files "zhdocs/cp/*.md" --exclude-standard)
        if [ ${#md_files[@]} -gt 0 ]; then
          echo "files_found=true" >> $GITHUB_OUTPUT
        else
          echo "files_found=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Commit Markdown files
      if: ${{ fromJSON(steps.check_files.outputs.files_found) }}
      run: |
        git add zhdocs/cp/*.md
        git commit -m "Add Markdown files" || echo "No changes to commit"
        git push  # 提交转换后的Markdown文件
      shell: bash