name: Convert Office Files to Markdown

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # MarkItDown需要Python 3.10或更高版本

    - name: Install MarkItDown
      run: pip install markitdown  # 安装MarkItDown库

    - name: Create output directory
      run: |
        mkdir -p zhdocs/cp  # 创建输出目录，如果不存在

    - name: Run conversion script
      run: |
        python convert_to_markdown.py
      shell: bash  # 使用bash shell执行脚本

    - name: Commit Markdown files
      run: |
        git config --local user.email "79011008+yunshuangqwq@users.noreply.github.com"
        git config --local user.name "yunshuangqwq"
        git add zhdocs/cp/*.md
        git commit -m "Add Markdown files" || echo "No changes to commit"
        git push  # 提交转换后的Markdown文件